# Generated by Django 3.2.4 on 2021-07-12 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_profile_buddy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='Profile',
            new_name='profile',
        ),
    ]
