# Generated by Django 3.2.4 on 2021-07-15 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20210715_1434'),
        ('main_app', '0020_auto_20210715_1225'),
    ]

    operations = [
    ]
