# Generated by Django 3.2.4 on 2021-07-16 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_alter_profile_timeslots'),
        ('main_app', '0023_auto_20210715_1709'),
        ('main_app', '0024_alter_profile_timeslots'),
    ]

    operations = [
    ]
